name: CICD with GitHub Actions

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Folder and Clone Repository
        run: |
          cd /var/www
          rm -rf cicd-test
          sudo git clone https://github.com/macabrepanpapakhin/cicd-test.git
          sudo cp cicd-test/index.html index.html
          pwd
          ls
          
          
