name: CICD with GitHub Actions

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Create Folder and Clone Repository
        run: |
          mkdir cicd
          cd abcdefg
          git clone https://github.com/IdeafreshMM/ideafresh.git
          cd ideafresh
          
